# SOME DESCRIPTIVE TITLE.
# Copyright (C) YEAR THE PACKAGE'S COPYRIGHT HOLDER
# This file is distributed under the same license as the PACKAGE package.
# FIRST AUTHOR <EMAIL@ADDRESS>, YEAR.
#
msgid ""
msgstr ""
"Project-Id-Version: 2.3.0\n"
"Report-Msgid-Bugs-To: \n"
"POT-Creation-Date: 2025-02-06 09:43+0100\n"
"PO-Revision-Date: 2024-10-01 14:10+0200\n"
"Last-Translator: Lorenzo Maiuri <lorenzo.maiuri@ik.me>\n"
"Language-Team: Italian <LL@li.org>\n"
"Language: it\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"

#: davinci_helper/functions/gui/check_update_dialog_gui.py:104
msgid "A new update is available"
msgstr "È disponibile un nuovo aggiornamento"

#: davinci_helper/functions/gui/check_update_dialog_gui.py:107
msgid ""
"A new version of this app has been found.\n"
"We recommend you to update it before continue using it."
msgstr ""
"È stata trovata una nuova versione di questa app.\n"
"Ti consigliamo di aggiornare l'app prima di continuare ad usarla."

#: davinci_helper/functions/gui/converter_dialog_gui.py:101
msgid "Select a valid file"
msgstr "Seleziona un file valido"

#: davinci_helper/functions/gui/converter_dialog_gui.py:104
msgid ""
"It seems like you didn't load any file to convert.\n"
"\n"
"Please load at least one supported video file to continue."
msgstr ""
"Sembra che tu non abbia caricato alcun file da convertire.\n"
"\n"
"Per favore, carica almeno un file video supportato per continuare."

#: davinci_helper/functions/gui/converter_dialog_gui.py:115
msgid "Select a valid file and output folder"
msgstr "Seleziona un file e una cartella di output validi"

#: davinci_helper/functions/gui/converter_dialog_gui.py:118
msgid ""
"It seems like you didn't load any file to convert\n"
"and you didn't choose any output folder.\n"
"\n"
"Please load at least one supported video file\n"
"and select a valid output folder to continue."
msgstr ""
"Sembra che tu non abbia caricato alcun file da convertire\n"
"e che non abbia scelto nessuna cartella di output.\n"
"\n"
"Per favore, carica almeno un file video supportato\n"
"e seleziona una cartella di output valida per continuare."

#: davinci_helper/functions/gui/converter_dialog_gui.py:128
msgid "Select a valid output folder"
msgstr "Seleziona una cartella di output valida"

#: davinci_helper/functions/gui/converter_dialog_gui.py:131
msgid ""
"It seems like you didn't load any output folder.\n"
"\n"
"Please select a valid output folder to continue."
msgstr ""
"Sembra che tu non abbia selezione alcuna cartella di output.\n"
"\n"
"Per favore, seleziona una cartella di output valida per continuare."

#: davinci_helper/functions/gui/converter_dialog_gui.py:141
msgid "Unsupported files found"
msgstr "Trovati file non supportati"

#: davinci_helper/functions/gui/converter_dialog_gui.py:144
msgid ""
"Some files can't be converted because they are unsupported.\n"
"If you decide to continue, the following file will not be converted :\n"
msgstr ""
"Alcuni file non possono essere convertiti perchè non sono supportati.\n"
"Se decidi di continuare, i seguenti file non verranno convertiti :\n"

#: davinci_helper/functions/gui/converter_dialog_gui.py:159
msgid "Continue"
msgstr "Continua"

#: davinci_helper/functions/gui/converter_dialog_gui.py:172
msgid "All the files have been converted"
msgstr "Tutti i file sono stati convertiti"

#: davinci_helper/functions/gui/converter_dialog_gui.py:175
msgid ""
"All your files have been correctly converted\n"
"and placed inside your designed folder."
msgstr ""
"Tutti i tuoi file sono stati convertiti correttamente\n"
"e salvati all’interno della cartella da te selezionata."

#: davinci_helper/functions/gui/converter_dialog_gui.py:185
msgid "Are you sure you want to exit ?"
msgstr "Sei sicuro di voler uscire ?"

#: davinci_helper/functions/gui/converter_dialog_gui.py:188
msgid ""
"The video conversion is still going on,\n"
"if you exit this app the process will be interupted and\n"
"you will get only the files converted\n"
"before the app closure."
msgstr ""
"La conversione dei video è ancora in corso,\n"
"se esci dall’app il processo verrà interrotto e\n"
"otterrai solo i file convertiti\n"
"prima della chiusura dell'app."

#: davinci_helper/functions/gui/converter_dialog_gui.py:191
msgid "Continue conversion"
msgstr "Continua la conversione"

#: davinci_helper/functions/gui/converter_dialog_gui.py:197
msgid "Exit app"
msgstr "Esci dall'app"

#: davinci_helper/functions/gui/file_error_dialog_gui.py:95
msgid "Select a valid file !"
msgstr "Seleziona un file valido !"

#: davinci_helper/functions/gui/file_error_dialog_gui.py:101
msgid ""
"It seems like you didn't load any file.\n"
"Please load a valid DaVinci Resolve installer zip file to continue."
msgstr ""
"Sembra che tu non abbia caricato nessun file.\n"
"Per favore, carica un file zip dell'installer di Davinci Resolve per "
"continuare."

#: davinci_helper/functions/gui/file_error_dialog_gui.py:106
msgid ""
"It seems like you tried to load an usupported file.\n"
"Please load a valid DaVinci Resolve installer zip file to continue.\n"
"If you have renamed it, remember that the file name must\n"
"contain the words 'DaVinci', 'Resolve', 'Linux' inside of it\n"
"and it must to have the '.zip' extension."
msgstr ""
"Sembra che tu abbia provato a caricare un file non supportato.\n"
"Per favore, carica un file zip dell'installer di DaVinci Resolve per "
"continuare.\n"
"Se lo hai rinominato, ricorda che il nome del file deve\n"
"contenere le parole 'DaVinci', 'Resolve', 'Linux' al suo interno\n"
"e deve avere l'estensione '.zip'."

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:109
msgid "This will need a lot of space !"
msgstr "Occuperà molto spazio !"

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:112
msgid ""
"The conversion of the files using the DNxHD/HR encoder will make new files "
"fully compatible with DaVinci Resolve Free.\n"
"\n"
"The use of these uncompressed sources will make your editing experience "
"faster, but it will take a lot of disk space.\n"
msgstr ""
"La conversione dei file usando l'encoder DNxHD/HR renderà i nuovi "
"filecompletamente compatibili con DaVinci Resolve Free.\n"
"\n"
"L'uso di queste fonti non compresse renderà la tua esperienza di editing più "
"veloce, ma occuperà molto spazio sul tuo disco.\n"

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:115
#, python-brace-format
msgid ""
"The estimated disk space needed to convert the files is :\n"
"{space_placeholder}GB\n"
msgstr ""
"Lo spazio necessario per convertire i file si stima sia :\n"
"{space_placeholder}GB\n"

#: davinci_helper/functions/gui/file_size_warning_dialog_gui.py:118
msgid ""
"If you want to use less disk space please consider using\n"
"lower video and audio settings."
msgstr ""
"Se vuoi utilizzare meno spazio del disco, prova ad utilizzare\n"
"impostazioni video e audio più basse."

#: davinci_helper/functions/gui/function_1_gui.py:152
msgid ""
"Check and install\n"
"missing dependencies"
msgstr ""
"Trova ed installa\n"
"le dipendenze mancanti"

#: davinci_helper/functions/gui/function_1_gui.py:155
msgid ""
"This part of the software will install all the dependencies necessary to "
"correctly launch the installation and the execution of DaVinci Resolve. The "
"script will detect your Fedora version and the libraries installed, after "
"that it will install only the packages needed. This script does not collect "
"or diffuse any information about you or your system. The internet connection "
"is required only if there are any missing libraries to install."
msgstr ""
"Questa parte del software installerà tutte le dipendenze necessarie per "
"avviare correttamente l'installazione e l'esecuzione di DaVinci Resolve. Lo "
"script rileverà la tua versione di Fedora e le librerie installate, "
"successivamente installerà solo i pacchetti mancanti. Questo script non "
"raccoglie o diffonde informazioni su di te o il tuo sistema. La connessione "
"internet è richiesta solo in caso ci siano librerie mancanti da installare."

#: davinci_helper/functions/gui/function_1_gui.py:208
#: davinci_helper/functions/gui/function_1_gui.py:239
#: davinci_helper/functions/gui/function_2_gui.py:220
#: davinci_helper/functions/gui/function_2_gui.py:248
#: davinci_helper/functions/gui/function_3_gui.py:208
#: davinci_helper/functions/gui/function_3_gui.py:239
#: davinci_helper/functions/gui/function_4_gui.py:208
#: davinci_helper/functions/gui/function_4_gui.py:239
msgid "Show Info"
msgstr "Mostra Info"

#: davinci_helper/functions/gui/function_1_gui.py:211
#: davinci_helper/functions/gui/function_1_gui.py:489
#: davinci_helper/functions/gui/function_2_gui.py:601
#: davinci_helper/functions/gui/function_3_gui.py:211
#: davinci_helper/functions/gui/function_3_gui.py:497
#: davinci_helper/functions/gui/function_4_gui.py:211
#: davinci_helper/functions/gui/function_4_gui.py:489
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:161
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:186
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:458
msgid "Show logs"
msgstr "Mostra log"

#: davinci_helper/functions/gui/function_1_gui.py:247
#: davinci_helper/functions/gui/function_2_gui.py:256
#: davinci_helper/functions/gui/function_3_gui.py:247
#: davinci_helper/functions/gui/function_4_gui.py:247
msgid "Hide info"
msgstr "Nascondi info"

#: davinci_helper/functions/gui/function_1_gui.py:406
msgid "The dependencies have been correctly installed"
msgstr "Le dipendenze sono state installate correttamente"

#: davinci_helper/functions/gui/function_1_gui.py:409
msgid ""
"All the dependencies have been correctly installed inside the system.\n"
"Now you can correctly start the DaVinci Resolve installer."
msgstr ""
"Tutte le dipendenze sono state correttamente installate nel sistema.\n"
"Ora puoi avviare senza errori l'installazione di DaVinci Resolve."

#: davinci_helper/functions/gui/function_1_gui.py:426
msgid "There was an error installing the dependencies"
msgstr "C'è stato un errore durante l'installazione delle dipendenze"

#: davinci_helper/functions/gui/function_1_gui.py:434
msgid ""
"There was an error getting what version of Fedora you are using.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore nella lettura della versione di Fedora in uso.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_1_gui.py:442
msgid ""
"There was an error getting the list of the installed libraries on your "
"system.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore nella lettura delle librerie installate nel tuo "
"sistema.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_1_gui.py:450
msgid ""
"There was an error during the installation of the missing libraries.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'installazione delle librerie mancanti.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_1_gui.py:458
#: davinci_helper/functions/gui/function_3_gui.py:466
#: davinci_helper/functions/gui/function_4_gui.py:458
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:427
msgid "You need to be an admin to use this function"
msgstr "Devi essere un admin per usare questa funzione"

#: davinci_helper/functions/gui/function_1_gui.py:461
#: davinci_helper/functions/gui/function_3_gui.py:469
#: davinci_helper/functions/gui/function_4_gui.py:461
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:430
msgid ""
"It was impossible to start this function because you didn't give the "
"necessary root permission for his execution. Try again giving the root "
"permission."
msgstr ""
"È stato impossibile avviare questa funzione perchè non hai dato i permessi "
"di root necessari per la sua esecuzione. Prova nuovamente fornendo i "
"permessi di root. "

#: davinci_helper/functions/gui/function_1_gui.py:497
#: davinci_helper/functions/gui/function_2_gui.py:609
#: davinci_helper/functions/gui/function_3_gui.py:505
#: davinci_helper/functions/gui/function_4_gui.py:497
#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:169
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:466
msgid "Hide logs"
msgstr "Nascondi log"

#: davinci_helper/functions/gui/function_2_gui.py:159
msgid ""
"Launch DaVinci Resolve\n"
"installation wizard"
msgstr ""
"Avvia l'installazione\n"
"di DaVinci Resolve"

#: davinci_helper/functions/gui/function_2_gui.py:162
msgid ""
"This part of the software will ask you to indicate the DaVinci Resolve "
"installer file path, then it will run it with the necessary patch to make it "
"launch properly."
msgstr ""
"Questa parte del software ti chiederà di indicare il percorso del file di "
"installazione di DaVinci Resolve, poi applicherà le modifiche necessarie per "
"avviarlo correttamente."

#: davinci_helper/functions/gui/function_2_gui.py:276
msgid "Select the DaVinci Resolve installer .zip file"
msgstr "Seleziona il file .zip dell'installer di DaVinci Resolve"

#: davinci_helper/functions/gui/function_2_gui.py:536
msgid "You have successfully started the DaVinci wizard"
msgstr "Hai avviato con successo l'installer di DaVinci"

#: davinci_helper/functions/gui/function_2_gui.py:539
msgid ""
"You have successfully started the DaVinci Resolve installation wizard.\n"
"Now you can install DaVinci Resolve on your computer."
msgstr ""
"Hai avviato con successo l'Installer di DaVinci Resolve.\n"
"Ora puoi installare DaVinci Resolve sul tuo computer. "

#: davinci_helper/functions/gui/function_2_gui.py:559
msgid "There was an error launching the DaVinci wizard"
msgstr "C'è stato un errore durante l'avvio dell'installer di DaVinci"

#: davinci_helper/functions/gui/function_2_gui.py:567
msgid ""
"There was an error extracting the DaVinci Resolve installer zip inside the "
"target folder.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'estrazione dell'installer di DaVinci Resolve "
"all'interno della cartella predefinita.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_2_gui.py:576
msgid ""
"There was an error launching the DaVinci Resolve installation wizard.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'avvio dell'installer di DaVinci Resolve.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_3_gui.py:152
msgid ""
"Apply the DaVinci Resolve\n"
"post installation fix"
msgstr ""
"Applica le correzioni post installazione\n"
"di DaVinci Resolve"

#: davinci_helper/functions/gui/function_3_gui.py:155
msgid ""
"This part of the software will put some of the dependencies shipped with "
"DaVinci Resolve in a safe folder, in order to make it use the system ones."
msgstr ""
"Questa parte del software trasferirà alcune delle dipendenze predefinite di "
"DaVinci Resolve in una cartella sicura, in modo da forzare l'utilizzo di "
"quelle di sistema."

#: davinci_helper/functions/gui/function_3_gui.py:406
msgid ""
"The post installation fix\n"
"has been correctly applied"
msgstr ""
"Le correzioni post installazione\n"
"sono state applicate correttamente"

#: davinci_helper/functions/gui/function_3_gui.py:409
msgid ""
"All the problematic libraries have been correctly moved inside the secure "
"folder.\n"
"Now you can correctly run DaVinci Resolve."
msgstr ""
"Tutte le librerie problematiche sono state spostate correttamente nella "
"cartella sicura.\n"
"Ora puoi avviare correttamente DaVinci Resolve."

#: davinci_helper/functions/gui/function_3_gui.py:426
msgid "There was an error applying the fixes"
msgstr "C'è stato un errore durante l'applicazione delle correzioni"

#: davinci_helper/functions/gui/function_3_gui.py:434
msgid ""
"There was an error finding the DaVinci Resolve installation folder.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore nel trovare la cartella di installazione di DaVinci "
"Resolve.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_3_gui.py:442
msgid ""
"There was an error finding a compatible version of DaVinci Resolve on your "
"system.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore nel trovare una versione compatibile di DaVinci Resolve "
"sul tuo sistema.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_3_gui.py:450
msgid ""
"There was an error during the creation of the libraries' secure folder.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante la creazione della cartella sicura per le "
"librerie.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_3_gui.py:458
msgid ""
"There was an error moving the libraries inside the secure folder.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante il trasferimento delle librerie nella cartella "
"sicura.\n"
"Per favore, controlla i log per avere maggiori dettagli."

#: davinci_helper/functions/gui/function_4_gui.py:152
msgid ""
"Check and install the\n"
"correct gpu drivers"
msgstr ""
"Trova ed installa i\n"
"corretti driver della GPU"

#: davinci_helper/functions/gui/function_4_gui.py:155
msgid ""
"This part of the software will check what GPU you are using and then, if it "
"is supported, it will check if the correct drivers are installed. If it "
"finds missing or outdated drivers the software will install them to make "
"your GPU fully support DaVinci Resolve."
msgstr ""
"Questa parte del software controllerà quali GPU sono presenti nel tuo "
"sistema. In caso ne sia trovata una supportata, il programma controllerà che "
"i driver corretti siano installati. In caso dovesse trovare driver mancanti "
"o datati, il programma li installerà per permettere alla tua GPU di "
"supportare DaVinci Resolve."

#: davinci_helper/functions/gui/function_4_gui.py:406
msgid "The GPUs drivers have been correctly installed"
msgstr "I driver della GPU sono stati installati correttamente"

#: davinci_helper/functions/gui/function_4_gui.py:409
msgid ""
"All the GPUs drivers have been correctly installed inside the system.\n"
"Now you can correctly run DaVinci Resolve."
msgstr ""
"Tutti i driver delle GPU sono stati installati correttamente all'interno del "
"sistema.\n"
"Ora puoi avviare correttamente DaVinci Resolve."

#: davinci_helper/functions/gui/function_4_gui.py:426
msgid "There was an error installing the GPUs drivers"
msgstr "C'è stato un errore durante l'installazione dei driver della GPU"

#: davinci_helper/functions/gui/function_4_gui.py:434
msgid ""
"There was an error finding a supported GPU inside your system.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore nel trovare una GPU supportata nel tuo sistema.\n"
"Per favore, controlla i log per avere maggiori dettagli. "

#: davinci_helper/functions/gui/function_4_gui.py:442
#: davinci_helper/functions/gui/ffmpeg_install_gui.py:387
msgid ""
"There was an error while adding the RPM Fusion repository to your system.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore nell'aggiungere il repository RPM Fusion al tuo "
"sistema.\n"
"Per favore, controlla i log per avere maggiori dettagli. "

#: davinci_helper/functions/gui/function_4_gui.py:450
msgid ""
"There was an error during the installation of the GPUs drivers.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'installazione dei driver delle GPU.\n"
"Per favore, controlla i log per avere maggiori dettagli. "

#: davinci_helper/functions/gui/function_5_gui.py:167
#: davinci_helper/main.py:353
msgid "DaVinci Video Converter"
msgstr "Converti video per DaVinci"

#: davinci_helper/functions/gui/function_5_gui.py:170
msgid "Exported video settings"
msgstr "Impostazioni dei video esportati"

#: davinci_helper/functions/gui/function_5_gui.py:195
msgid ""
"The time needed to complete this task will vary\n"
"on your computer and network performance."
msgstr ""
"Il tempo necessario per completare questa operazione può variare\n"
"a seconda delle performance tuo PC e della tua connessione di rete."

#: davinci_helper/functions/gui/function_5_gui.py:298
msgid "Select the converted videos output folder"
msgstr "Seleziona la cartella di output deI video convertiti"

#: davinci_helper/functions/gui/function_5_gui.py:355
msgid "Select the files to convert"
msgstr "Seleziona i file da convertire"

#: davinci_helper/functions/gui/function_5_gui.py:906
#, python-brace-format
msgid "Converting the file : {file_name}"
msgstr "Convertendo il file : {file_name}"

#: davinci_helper/functions/gui/function_5_gui.py:951
#, python-brace-format
msgid "Finished processing the file : {file_name}"
msgstr "La conversione del file {file_name} è stata completata"

#: davinci_helper/functions/gui/function_5_gui.py:957
#, python-brace-format
msgid "{self.file_name} - 100%"
msgstr "{file_name} - 100%"

#: davinci_helper/functions/gui/function_5_gui.py:1020
msgid "{self.file_name} - {progress * 100:.2f}%"
msgstr "{file_name} - {avanzamento * 100:.2f}%"

#: davinci_helper/functions/gui/function_5_gui.py:1042
msgid "Starting with the next file..."
msgstr "Iniziando il prossimo file..."

#: davinci_helper/functions/gui/loading_gui.py:92
msgid ""
"The time needed to complete this task will vary on your computer and network "
"performance."
msgstr ""
"Il tempo necessario al completamento di questa operazione può variare a "
"seconda delle performance del tuo PC e della tua connessione di rete. "

#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:107
msgid "There are some missing modules"
msgstr "Ci sono alcuni moduli mancanti"

#: davinci_helper/functions/gui/module_install_error_dialog_guy.py:110
msgid ""
"There was an error installing the Moviepy python module.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'installazione del modulo python Moviepy.\n"
"Per favore, controlla i logs per avere più dettagli."

#: davinci_helper/functions/gui/settings_management_dialog_gui.py:98
msgid "Settings restored successfully"
msgstr "Impostazioni ripristinate con successo"

#: davinci_helper/functions/gui/settings_management_dialog_gui.py:101
msgid ""
"The default app settings have been restored successfully.\n"
"If you are still experiencing any error or bug,\n"
"please contact us on the <a href=\"https://github.com/H3rz3n/davinci-helper/"
"issues\">project GitHub page</a>"
msgstr ""
"Le impostazioni di default dell'app sono state ripristinate con successo.\n"
"Se stai ancora riscontrando errori o bug,\n"
"per favore, contattaci sulla <a href=\"https://github.com/H3rz3n/davinci-"
"helper/issues\">pagina GitHub del progetto</a>"

#: davinci_helper/functions/gui/start_screen_gui.py:151
msgid "Welcome to DaVinci Helper"
msgstr "Benvenuto in DaVinci Helper"

#: davinci_helper/functions/gui/start_screen_gui.py:154
msgid "The best tool for managing DaVinci Resolve on Linux"
msgstr "Il migliore strumento per gestire DaVinci Resolve su Linux"

#: davinci_helper/functions/gui/welcome_dialog_gui.py:114
msgid ""
"Thank you for installing\n"
"DaVinci Helper"
msgstr ""
"Grazie per aver installato\n"
"DaVinci Helper"

#: davinci_helper/functions/gui/welcome_dialog_gui.py:117
msgid ""
"Thank you for trusting us and installing DaVinci Helper. We hope that this "
"app will make the management of DaVinci Resolve easier for you.\n"
msgstr ""
"Grazie per averci dato fiducia ed aver installato DaVinci Helper.\n"
"Speriamo che questa app vi semplifichi l'utilizzo di DaVinci Resolve su "
"Linux.\n"

#: davinci_helper/functions/gui/welcome_dialog_gui.py:120
msgid ""
"This app is not affiliated in any way with BlackMagic Design, it's only a "
"community project and comes without any guarantees.\n"
msgstr ""
"Questa app non è in nessun modo associata a BlackMagic Design,\n"
"è un progetto realizzato dalla commmunity e non possiede alcuna garanzia.\n"

#: davinci_helper/functions/gui/welcome_dialog_gui.py:123
msgid ""
"If you find this app useful and want to improve it please consider helping "
"us <a href=\"https://github.com/H3rz3n/davinci-helper\">developing</a> this "
"app or <a href=\"https://www.paypal.com/donate/?"
"hosted_button_id=CPCG2RFAV82T8\">making a donation</a>  to the project."
msgstr ""
"Se trovi questa app utile a vorresti migliorarla, puoi aiutarci \n"
"a <a href=\"https://github.com/H3rz3n/davinci-helper\">svilupparla</a> "
"oppure <a href=\"https://www.paypal.com/donate/?"
"hosted_button_id=CPCG2RFAV82T8\">facendo una donazione</a> al progetto. "

#: davinci_helper/functions/gui/welcome_dialog_gui.py:127
msgid "Don't show again"
msgstr "Non mostrare di nuovo"

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:142
msgid ""
"Install FFMPEG\n"
"to use this feature"
msgstr ""
"Installa FFMPEG\n"
"per usare questa funzione"

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:347
msgid "FFMPEG was successfully installed"
msgstr "FFMPEG è stato installato con successo"

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:350
msgid ""
"FFMPEG has been correctly installed inside the system.\n"
"Now you can start using DaVinci Video Convert."
msgstr ""
"FFMPEG è stato correttamente installato nel sistema.\n"
"Ora puoi iniziare convertire i video di DaVinci."

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:353
msgid "Go to DaVinci Video Converter"
msgstr "Converti video per DaVinci"

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:373
msgid "There was an error installing FFMPEG"
msgstr "C'è stato un errore durante l'installazione di FFMPEG"

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:395
msgid ""
"There was an error installing FFMPEG from the RPM Fusion repository.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'installazione di FFMPEG dal repository RPM "
"Fusion.\n"
"Per favore, controlla i logs per avere più dettagli."

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:403
msgid ""
"There was an error swapping FFMPEG lite with\n"
"FFMPEG full from the RPM Fusion repository.\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante lo scambio di FFMPEG Lite con\n"
"FFMPEG Full dal repository RPM Fusion.\n"
"Per favore, controlla i logs per avere più dettagli."

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:411
msgid ""
"There was an error installing the required codecs\n"
"and libraries from the RPM Fusion repository\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'installazione di FFMPEG dal repository RPM "
"Fusion.\n"
"Per favore, controlla i logs per avere più dettagli."

#: davinci_helper/functions/gui/ffmpeg_install_gui.py:419
msgid ""
"There was an error updating the multimedia group\n"
"Please check the logs to have more details."
msgstr ""
"C'è stato un errore durante l'aggiornamento dei codec.\n"
"Per favore, controlla i logs per avere più dettagli."

#: davinci_helper/functions/logic/function_1.py:57
#: davinci_helper/functions/logic/function_1.py:65
#: davinci_helper/functions/logic/function_1.py:74
#: davinci_helper/functions/logic/function_1.py:82
#, python-brace-format
msgid "You are using a supported OS version : {os_version_placeholder}"
msgstr ""
"Stai utilizzando un sistema operativo supportato : {os_version_placeholder}"

#: davinci_helper/functions/logic/function_1.py:88
msgid "DEBUG : There was an error reading what OS is installed :"
msgstr ""
"DEBUG : C'è stato un errore durante la lettura della versione di Fedora in "
"uso :"

#: davinci_helper/functions/logic/function_1.py:92
#: davinci_helper/functions/logic/function_1.py:123
#: davinci_helper/functions/logic/function_1.py:265
#: davinci_helper/functions/logic/function_2.py:74
#: davinci_helper/functions/logic/function_2.py:94
#: davinci_helper/functions/logic/function_3.py:58
#: davinci_helper/functions/logic/function_3.py:165
#: davinci_helper/functions/logic/function_3.py:184
#: davinci_helper/functions/logic/function_4.py:76
#: davinci_helper/functions/logic/function_4.py:125
#: davinci_helper/functions/logic/function_4.py:173
#: davinci_helper/functions/logic/function_4.py:201
#: davinci_helper/functions/logic/function_4.py:249
#: davinci_helper/functions/logic/function_4.py:283
#: davinci_helper/functions/logic/install_ffmpeg.py:107
#: davinci_helper/functions/logic/install_ffmpeg.py:141
#: davinci_helper/functions/logic/install_ffmpeg.py:175
#: davinci_helper/functions/logic/install_ffmpeg.py:337
#: davinci_helper/functions/logic/install_ffmpeg.py:371
msgid ""
"Please open an issue report and paste this error code on the project GitHub "
"page :"
msgstr ""
"Per favore, apri una segnalazione e copia questo codice di errore nella "
"pagina GitHub dedicata :"

#: davinci_helper/functions/logic/function_1.py:120
msgid "DEBUG : There was an error reading the library list :"
msgstr ""
"DEBUG : C'è stato un errore durante la lettura della lista della librerie "
"installate"

#: davinci_helper/functions/logic/function_1.py:172
#: davinci_helper/functions/logic/function_1.py:228
#: davinci_helper/functions/logic/install_ffmpeg.py:299
msgid "The following libraries will be installed because they are missing :"
msgstr "Le seguenti librerie saranno installate perchè sono mancanti :"

#: davinci_helper/functions/logic/function_1.py:182
#: davinci_helper/functions/logic/function_1.py:238
msgid ""
"There are no missing libraries to install, you can now install DaVinci "
"Resolve"
msgstr ""
"Non ci sono librerie mancanti da installare, ora puoi installare DaVinci "
"Resolve"

#: davinci_helper/functions/logic/function_1.py:261
msgid "DEBUG : There was an error installing the missing libraries :"
msgstr ""
"DEBUG : C'è stato un errore durante l'installazione delle librerie mancanti :"

#: davinci_helper/functions/logic/function_2.py:71
msgid "DEBUG : There was an error extracting the DaVinci Resolve installer :"
msgstr ""
"DEBUG : C'è stato un errore durante l'estrazione dell'installer di DaVinci "
"Resolve :"

#: davinci_helper/functions/logic/function_2.py:91
msgid ""
"DEBUG : There was an error launching the DaVinci Resolve installation "
"wizard :"
msgstr ""
"DEBUG : C'è stato un errore durante l'avvio dell'installer di DaVinci Resolve"

#: davinci_helper/functions/logic/function_3.py:55
msgid ""
"DEBUG : It was impossible to find the DaVinci Resolve installation folder "
"in /opt/resolve."
msgstr ""
"DEBUG : È stato impossibile trovare la cartella di installazione di DaVinci "
"Resolve in /opt/resolve."

#: davinci_helper/functions/logic/function_3.py:56
msgid ""
"If you haven't done it already, please install DaVinci Resolve and try again."
msgstr ""
"Se non l'hai già fatto, per favore installa DaVinci Resolve e prova di nuovo."

#: davinci_helper/functions/logic/function_3.py:75
msgid "DaVinci Resolve 18.x.x was found in the system"
msgstr "DaVinci Resolve 18.x.x è stato trovato nel sistema"

#: davinci_helper/functions/logic/function_3.py:85
msgid "DaVinci Resolve 19.x.x was found in the system"
msgstr "DaVinci Resolve 19.x.x è stato trovato nel sistema"

#: davinci_helper/functions/logic/function_3.py:94
msgid ""
"DEBUG : An installed version of DaVinci that is not currently supported was "
"found."
msgstr ""
"DEBUG : È stata trovata installata una versione di DaVinci Resolve che al "
"momento non è supportata."

#: davinci_helper/functions/logic/function_3.py:95
msgid ""
"Please visit the GitHub page to find which version of DaVinci Resolve are "
"supported."
msgstr ""
"Per favore, visita la pagina di GitHub per scoprire quali versioni di "
"DaVinci Resolve sono supportate."

#: davinci_helper/functions/logic/function_3.py:139
msgid ""
"The libraries were already moved inside the secure folder. There was no need "
"to do anything."
msgstr ""
"Le librerie sono già state sportate nella cartelle sicura. Non c'è stato "
"bisogno di fare altro."

#: davinci_helper/functions/logic/function_3.py:149
msgid "The following libraries will be moved in a secure folder :"
msgstr "Le seguenti librerie saranno spostate in una cartella sicura :"

#: davinci_helper/functions/logic/function_3.py:162
msgid ""
"DEBUG : It was impossible to create the secure folder where to move the "
"libraries in /opt/resolve/libs/disabled_libraries."
msgstr ""
"DEBUG : È stato impossibile creare una cartella sicura in cui spostare le "
"librerie in /opt/resolve/libs/disabled_libraries."

#: davinci_helper/functions/logic/function_3.py:163
msgid "Try again granting the app root permission or create it by yourself."
msgstr ""
"Prova di nuovo concedendo all'app i permessi di root o crea la cartella tu "
"stesso."

#: davinci_helper/functions/logic/function_3.py:182
msgid ""
"DEBUG : There was an error moving the libraries inside the secure folder in /"
"opt/resolve/libs/disabled_libraries. Try again granting the app root "
"permission or move it by yourself."
msgstr ""
"DEBUG : C'è stato un errore durante lo spostamento delle librerie nella "
"cartella sicura in/opt/resolve/libs/disabled_libraries. Prova di nuovo "
"concedendo all'app i permessidi root o spostala tu stesso."

#: davinci_helper/functions/logic/function_3.py:195
msgid "The libraries were correctly moved inside the secure folder."
msgstr "Le librerie sono state spostate correttamente nella cartella sicura."

#: davinci_helper/functions/logic/function_4.py:59
#: davinci_helper/functions/logic/install_ffmpeg.py:90
msgid ""
"The RPM Fusion repository had already been added to the system, there was no "
"need to add it."
msgstr ""
"Il repository RPM Fusion era già presente nel sistema, non c'è stato bisogno "
"di aggiungerlo."

#: davinci_helper/functions/logic/function_4.py:71
#: davinci_helper/functions/logic/install_ffmpeg.py:102
msgid ""
"DEBUG : It was impossible to add the RPM Fusion Free and Non-Free repository."
msgstr ""
"DEBUG : È stato impossibile aggiungere i repository RPM Fusion Free e Non-"
"Free."

#: davinci_helper/functions/logic/function_4.py:72
#: davinci_helper/functions/logic/install_ffmpeg.py:103
msgid "Check your network connection and try again or add it by yourself."
msgstr ""
"Controlla la tua connessione ad internet e prova di nuovo oppure aggiungili "
"tu stesso."

#: davinci_helper/functions/logic/function_4.py:85
#: davinci_helper/functions/logic/install_ffmpeg.py:116
msgid ""
"The RPM Fusion Free and Non-Free repository have been successfully added."
msgstr ""
"I repository RPM Fusion Free e Non-Free sono stati aggiunti con successo."

#: davinci_helper/functions/logic/function_4.py:108
msgid ""
"The proprietary Nvidia GPU driver was already installed on the system, there "
"was no need to install it."
msgstr ""
"Il driver proprietario della GPU Nvidia era già installato nel sistema, non "
"c'è stato bisogno di installarlo."

#: davinci_helper/functions/logic/function_4.py:120
msgid "DEBUG : It was impossible to install the proprietary Nvidia GPU driver."
msgstr ""
"DEBUG : È stato impossibile installare il driver proprietario della GPU "
"Nvidia."

#: davinci_helper/functions/logic/function_4.py:121
#: davinci_helper/functions/logic/function_4.py:169
#: davinci_helper/functions/logic/function_4.py:197
#: davinci_helper/functions/logic/function_4.py:245
#: davinci_helper/functions/logic/function_4.py:279
msgid "Check your network connection and try again or install it by yourself."
msgstr ""
"Controlla la tua connessione ad internet e prova di nuovo o installalo tu "
"stesso."

#: davinci_helper/functions/logic/function_4.py:133
msgid "The proprietary Nvidia GPU driver has been successfully installed."
msgstr ""
"Il driver proprietario della GPU Nvidia è stato installato con successo."

#: davinci_helper/functions/logic/function_4.py:156
msgid ""
"The open source AMD GPU driver was already installed on the system, there "
"was no need to install it."
msgstr ""
"Il driver open source della GPU AMD era già installato nel sistema, non c'è "
"stato bisogno di installarlo."

#: davinci_helper/functions/logic/function_4.py:168
msgid "DEBUG : It was impossible to install the open source AMD GPU driver."
msgstr ""
"DEBUG : È stato impossibile installare il driver open source della GPU AMD."

#: davinci_helper/functions/logic/function_4.py:184
#: davinci_helper/functions/logic/function_4.py:266
msgid ""
"The MESA Freeworld drivers were already installed on the system, there was "
"no need to install it."
msgstr ""
"I driver MESA Freeworld erano già installati nel sistema, non c'è "
"stato bisogno di installarli."

#: davinci_helper/functions/logic/function_4.py:196
#: davinci_helper/functions/logic/function_4.py:278
msgid ""
"DEBUG : It was impossible to swap the MESA GPU driver with the complete "
"version."
msgstr ""
"DEBUG : È stato impossibile scambiare i driver GPU MESA GPU con la loro versione completa."

#: davinci_helper/functions/logic/function_4.py:209
#: davinci_helper/functions/logic/function_4.py:291
msgid ""
"The MESA GPU driver has been successfully swapped with the complete version."
msgstr ""
"I driver GPU MESA sono stati correttamente scambiati con la loro versione completa."

#: davinci_helper/functions/logic/function_4.py:232
msgid ""
"The complete Intel GPU driver was already installed on the system, there was "
"no need to install it."
msgstr ""
"La versione completa dei driver Intel era già presente nel sistema e non è stato necessario installarla."

#: davinci_helper/functions/logic/function_4.py:244
msgid "DEBUG : It was impossible to install the complete Intel GPU driver."
msgstr ""
"DEBUG : È stato impossibile installare la versione completa dei driver intel."

#: davinci_helper/functions/logic/function_4.py:257
msgid "The complete Intel driver has been successfully installed."
msgstr ""
"La versione completa dei driver Intel è stata installata con successo."

#: davinci_helper/functions/logic/install_ffmpeg.py:137
msgid "DEBUG : It was impossible to install FFMPEG from RPM Fusion."
msgstr "DEBUG : È stato impossibile installare FFMPEG da RPM Fusion"

#: davinci_helper/functions/logic/install_ffmpeg.py:150
msgid ""
"FFMPEG was successfully installed from RPM Fusion. Now you can use DaVinci "
"Converter "
msgstr ""
"FFMPEG è stato installato con successo da RPM Fusion. Ora puoi usare DaVinci "
"Converter "

#: davinci_helper/functions/logic/install_ffmpeg.py:171
msgid ""
"DEBUG : It was impossible to swap the lite version FFMPEG with the one from "
"RPM Fusion."
msgstr ""
"DEBUG : È stato impossibile scambiare la versione Lite di FFMPEG con quella "
"completa da RPM Fusion."

#: davinci_helper/functions/logic/install_ffmpeg.py:184
msgid ""
"FFMPEG lite was successfully swapped with FFMPEG full from RPM Fusion. Now "
"you can use DaVinci Converter "
msgstr ""
"FFMPEG Lite è stato scambiato con successo con FFMPEG Full da RPM Fusion. "
"Orapuoi usare DaVinci Converter "

#: davinci_helper/functions/logic/install_ffmpeg.py:309
msgid ""
"There are no missing codecs and libraries to install, you can now use "
"DaVinci Converter"
msgstr ""
"Non ci sono codec multimediali e librerie mancanti da installare, ora puoi "
"utilizzare DaVinci Video Converter"

#: davinci_helper/functions/logic/install_ffmpeg.py:333
msgid ""
"DEBUG : It was impossible to install the codecs and other libraries from RPM "
"Fusion."
msgstr ""
"DEBUG : È stato impossibile installare i codec e le altre librerie richiete "
"da RPM Fusion"

#: davinci_helper/functions/logic/install_ffmpeg.py:346
#: davinci_helper/functions/logic/install_ffmpeg.py:380
msgid ""
"All the codecs and missing libraries were successfully installed from RPM "
"Fusion. Now you can use DaVinci Converter"
msgstr ""
"Tutti i codec e librerie mancanti sono stati installati con successo da RPM "
"Fusion. Ora puoi usare DaVinci Video Converter "

#: davinci_helper/functions/logic/install_ffmpeg.py:367
msgid "DEBUG : It was impossible to update the multimedia group."
msgstr "DEBUG : È stato impossibile aggiornare i codec multimediali."

#: davinci_helper/functions/logic/install_ffmpeg.py:440
msgid ""
"FFMPEG was already installed on the system\n"
"there was no need to install it."
msgstr ""
"FFMPEG era già installato nel sistema\n"
"non c'è stato bisogno di installarlo."

#: davinci_helper/functions/logic/install_ffmpeg.py:481
msgid ""
"All the codecs and libraries were already installed\n"
"on the system, there was no need to install it."
msgstr ""
"Tutti i codec multimedali e librerie necessarie erano già installati nel "
"sistema, non c'è stato bisogno di installarli."

#: davinci_helper/main.py:341
msgid "Install missing dependencies"
msgstr "Installa le dipendenze mancanti"

#: davinci_helper/main.py:344
msgid "Launch DaVinci Resolve installer"
msgstr "Avvia l'installer di DaVinci Resolve"

#: davinci_helper/main.py:347
msgid "Apply post installation fix"
msgstr "Applica le correzioni post installazione"

#: davinci_helper/main.py:350
msgid "Check and install GPU drivers"
msgstr "Controlla e installa i driver della GPU"
